### ISSUE TITLE
Demos would be awesome

### ISSUE THREAD

**Issue by ColCh** [edravis/logatim#14]
For clientside (GH Pages, or JSBin) and serverside (Runnable?)

May be separate **examples** directory? Would be helpful to took at lib before downloading it. Thanks!

**Comment by sospedra** [comment]
Yaay! You're right! I'm gonna be working on this this afternoon. I think I'll also add some gifs or asciinema showing the features. Thanks for the touch ;)

**Comment by sospedra** [comment]
I added the Demo section and a link to the logatim sandbox here: eaadff6383767817c67539c52d1c70ac3e6febf0

Thanks for the suggestion! :+1:
